services:
  - type: web
    name: mcp-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GITHUB_TOKEN
        sync: false
      - key: JIRA_URL
        sync: false
      - key: JIRA_USERNAME
        sync: false
      - key: JIRA_API_TOKEN
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false